### ISSUE TITLE
Unequal sizes of the deploy bar tabs

### ISSUE THREAD

**Issue by anshulwadhawan** [loklak/dev.loklak.org#11]
These tabs are unequally sized.It would be better if they were equally sized both in terms of height and width.

![issue](https://user-images.githubusercontent.com/25061477/31045651-2997ae96-a606-11e7-9f8b-d57e4f8dbd4e.png)

**Comment by anshulwadhawan** [comment]
Please assign me this task !

**Comment by mariobehling** [comment]
Please follow up here and help to build a dedicated theme for loklak: https://github.com/loklak/sphinx_loklak_theme/
