### ISSUE TITLE
Optimize search bar

### ISSUE THREAD

**Issue by anshulwadhawan** [loklak/dev.loklak.org#12]
The Go button should be on the immediate right of the search bar rather than being on a new line

**Comment by mariobehling** [comment]
Screenshot?

**Comment by anshulwadhawan** [comment]
![issue2](https://user-images.githubusercontent.com/25061477/31045928-4e62b24c-a60c-11e7-8254-b0f2eab03a4f.png)

**Comment by mariobehling** [comment]
Ok, looks like you have good ideas. The theme that is used is a standard Sphinx theme. Instead of changing this theme, could you help to create a new theme for loklak?

I have imported the SUSI AI theme that we can use to start this here https://github.com/loklak/sphinx_loklak_theme/tree/master

**Comment by anshulwadhawan** [comment]
The thing is that I don't have any knowledge of python.Hence, I don't know how to change the current theme to the SUSI AI theme.However,I can create a UI just like the SUSI AI theme but it would be by making the changes in the current theme.
If you allow me to proceed,I will start working on it and propose a list of the required changes.

**Comment by mariobehling** [comment]
Thanks, but these changes will make it incompatible to future versions of the same theme. Maybe check if you start to learn more step by step. We need improvements in the SUSI.AI docs theme here https://github.com/fossasia/sphinx_susiai_theme as well. The theme is used each time we deploy the site. If you have more questions ask here: https://gitter.im/fossasia/yaydoc

Closing this then. Cheers.
